apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  project: default
  source:
    chart: redis-operator
    repoURL: https://github.com/spotahome/redis-operator/releases/tag/Chart-3.2.4
    targetRevision: 1.16.1
    helm:
      releaseName: redis-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redis-operator

